spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: file:${file.upload-dir},classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  servlet:
    multipart:
      max-file-size: 10MB
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_security_jwt?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000
    key: f58321420b5322e266a7364f9169faefff2f497265d90b1d5145071f301111ce
file:
  upload-dir: D:/user_file/
web3j:
  http-timeout-seconds: 300
  client-address: http://127.0.0.1:7545
  #  private
  dc: "new"
  tc: "new"
  uc: "new"
# App Properties