web3j:
  http-timeout-seconds: 300
  client-address: http://127.0.0.1:7545
  #  private
  dc: "new"
  tc: "new"
  uc: "new"
# App Properties


spring:
  jpa:
    hibernate:
      ddl-auto: create
  resources:
    static-locations: file:${file.upload-dir},classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
file:
  upload-dir: D:/user_file/